// Starter/demo data shown before the user adds their own albums.
export const SEED_LISTENED = [
  { id:"l1",  artist:"Kendrick Lamar", album:"Overly Dedicated",                  year:2010, genre:"hiphop",  rating:null },
  { id:"l2",  artist:"Kendrick Lamar", album:"Section.80",                        year:2011, genre:"hiphop",  rating:null },
  { id:"l3",  artist:"Kendrick Lamar", album:"good kid, m.A.A.d city",            year:2012, genre:"hiphop",  rating:null },
  { id:"l4",  artist:"Kendrick Lamar", album:"To Pimp a Butterfly",               year:2015, genre:"hiphop",  rating:null },
  { id:"l5",  artist:"Kendrick Lamar", album:"untitled unmastered.",              year:2016, genre:"hiphop",  rating:null },
  { id:"l6",  artist:"Kendrick Lamar", album:"DAMN.",                             year:2017, genre:"hiphop",  rating:null },
  { id:"l7",  artist:"Kendrick Lamar", album:"Mr. Morale & the Big Steppers",     year:2022, genre:"hiphop",  rating:null },
  { id:"l8",  artist:"Kendrick Lamar", album:"GNX",                               year:2024, genre:"hiphop",  rating:null },
  { id:"l9",  artist:"Kanye West",     album:"The College Dropout",               year:2004, genre:"hiphop",  rating:null },
  { id:"l10", artist:"Kanye West",     album:"Late Registration",                 year:2005, genre:"hiphop",  rating:null },
  { id:"l11", artist:"Kanye West",     album:"Graduation",                        year:2007, genre:"hiphop",  rating:null },
  { id:"l12", artist:"Kanye West",     album:"My Beautiful Dark Twisted Fantasy", year:2010, genre:"hiphop",  rating:null },
  { id:"l13", artist:"J. Cole",        album:"2014 Forest Hills Drive",           year:2014, genre:"hiphop",  rating:null },
  { id:"l14", artist:"J. Cole",        album:"For Your Eyez Only",                year:2016, genre:"hiphop",  rating:null },
  { id:"l15", artist:"J. Cole",        album:"KOD",                               year:2018, genre:"hiphop",  rating:null },
  { id:"l16", artist:"J. Cole",        album:"The Off-Season",                    year:2021, genre:"hiphop",  rating:null },
  { id:"l17", artist:"J. Cole",        album:"The Fall Off",                      year:2025, genre:"hiphop",  rating:null },
  { id:"l18", artist:"Freddie Gibbs & Madlib",        album:"Piñata",             year:2014, genre:"hiphop",  rating:null },
  { id:"l19", artist:"Freddie Gibbs & The Alchemist", album:"Alfredo",            year:2020, genre:"hiphop",  rating:null },
  { id:"l20", artist:"Freddie Gibbs & The Alchemist", album:"Alfredo 2",          year:2024, genre:"hiphop",  rating:null },
  { id:"l21", artist:"Baby Keem",      album:"Ca$ino",                            year:2026, genre:"hiphop",  rating:null },
  { id:"l22", artist:"Clipse",         album:"Let God Sort Em Out",               year:2025, genre:"hiphop",  rating:null },
  { id:"l23", artist:"Fleetwood Mac",  album:"Rumours",                           year:1977, genre:"rock",    rating:null },
  { id:"l24", artist:"Pink Floyd",     album:"The Dark Side of the Moon",         year:1973, genre:"rock",    rating:null },
  { id:"l25", artist:"Radiohead",      album:"In Rainbows",                       year:2007, genre:"alternative", rating:null },
  { id:"l26", artist:"Steely Dan",     album:"Aja",                               year:1977, genre:"jazz",    rating:null },
  { id:"l27", artist:"The Strokes",    album:"Is This It",                        year:2001, genre:"indie",   rating:null },
  { id:"l28", artist:"Jeff Buckley",   album:"Grace",                             year:1994, genre:"alternative", rating:null },
  { id:"l29", artist:"JID",            album:"The Never Story",                   year:2017, genre:"hiphop",  rating:null },
  { id:"l30", artist:"JID",            album:"DiCaprio 2",                        year:2018, genre:"hiphop",  rating:null },
  { id:"l31", artist:"JID",            album:"The Forever Story",                 year:2022, genre:"hiphop",  rating:null },
  { id:"l32", artist:"JID",            album:"Luv Is 4Ever",                      year:2024, genre:"hiphop",  rating:null },
  { id:"l33", artist:"Joey Bada$$",    album:"1999",                              year:2012, genre:"hiphop",  rating:null },
  { id:"l34", artist:"Common",         album:"Like Water for Chocolate",          year:2000, genre:"hiphop",  rating:null },
];
